[package]
name = "signDataRust"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
secp256k1 = "0.29.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.128"
sha2 = "0.10.8"
